<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.astrsomn</groupId>
        <artifactId>Astrsomn</artifactId>
        <version>0.1.0-alpha.1</version>
    </parent>

    <artifactId>astrsomn-workflow-springboot-starter</artifactId>
    <version>0.1.0-alpha.1</version>
    <name>astrsomn-workflow-springboot-starter</name>
    <description>Astrsomn workflow spring boot starter module</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
