-- ASTRSOMN 数据库初始化脚本
-- FLYWAY 版本: V1
-- 创建时间: 2026-05-08

-- 在此添加数据库初始化DDL语句
-- 示例:
-- CREATE TABLE  IF NOT EXISTS EXAMPLE (
--     ID BIGINT PRIMARY KEY AUTO_INCREMENT,
--     NAME VARCHAR(255) NOT NULL,
--     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- 注意: 请确保SQL语句以分号结尾
-- ASTRO_AI.AI_ACCOUNT DEFINITION

CREATE TABLE IF NOT EXISTS AI_ACCOUNT
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    API_KEY VARCHAR
(
    500
) DEFAULT NULL,
    API_SECRET VARCHAR
(
    500
) DEFAULT NULL,
    ACCOUNT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    ACCOUNT_NAME VARCHAR
(
    100
) DEFAULT NULL,
    ACCOUNT_TOKENS BIGINT DEFAULT NULL,
    API_URL VARCHAR
(
    100
) DEFAULT NULL,
    EXTENSION_CODE VARCHAR
(
    100
) DEFAULT NULL,
    STATUS VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );


-- ASTRO_AI.AI_AGENT DEFINITION

CREATE TABLE IF NOT EXISTS AI_AGENT
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    DESCRIPTION TEXT,
    AGENT_KEY VARCHAR
(
    255
) DEFAULT NULL,
    WORKFLOW_KEY VARCHAR
(
    128
) DEFAULT NULL,
    PROMPT_KEY VARCHAR
(
    255
) DEFAULT NULL,
    AGENT_NAME VARCHAR
(
    255
) DEFAULT NULL,
    KNOWLEDGE_BASE_KEYS TEXT,
    TOOL_KEYS TEXT,
    MCP_KEYS TEXT,
    MEMORY_MODE VARCHAR
(
    50
) DEFAULT NULL,
    MEMORY_WINDOW_SIZE VARCHAR
(
    50
) DEFAULT NULL,
    MAX_TOKENS INT DEFAULT NULL,
    ENABLE_STREAM TINYINT DEFAULT NULL,
    IS_DEFAULT VARCHAR
(
    100
) DEFAULT NULL,
    ROUTE_STRATEGY VARCHAR
(
    50
) DEFAULT NULL,
    AGENT_AVATAR VARCHAR
(
    500
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_AGENT_AGENT_KEY_AI_AGENT ON AI_AGENT (AGENT_KEY);
CREATE INDEX IDX_AI_AGENT_STATUS_AI_AGENT ON AI_AGENT (STATUS);
CREATE INDEX IDX_AI_AGENT_DELETED_AI_AGENT ON AI_AGENT (DELETED);


-- ASTRO_AI.AI_CHAT_MESSAGE DEFINITION

CREATE TABLE IF NOT EXISTS AI_CHAT_MESSAGE
(
    ID
    BIGINT
    NOT
    NULL,
    MEMORY_KEY
    VARCHAR
(
    128
) NOT NULL,
    TURN_NO INT DEFAULT NULL,
    MESSAGE_ORDER INT DEFAULT NULL,
    ROLE VARCHAR
(
    32
) DEFAULT NULL,
    MESSAGE_TYPE VARCHAR
(
    32
) DEFAULT NULL,
    CONTENT LONGTEXT,
    RESPONSE_STATUS VARCHAR
(
    32
) DEFAULT NULL,
    FINISH_REASON VARCHAR
(
    64
) DEFAULT NULL,
    PROMPT_TOKENS INT DEFAULT '0',
    COMPLETION_TOKENS INT DEFAULT '0',
    TOTAL_TOKENS INT DEFAULT '0',
    TRACE_ID VARCHAR
(
    128
) DEFAULT NULL,
    ERROR_CODE VARCHAR
(
    64
) DEFAULT NULL,
    AGENT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    INSTANCE_KEY VARCHAR
(
    128
) DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    128
) DEFAULT NULL,
    ACCOUNT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    PROMPT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    EXT_JSON LONGTEXT,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT NOT NULL DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_CHAT_MESSAGE_MEMORY_ORDER_AI_CHAT_MESSAGE ON AI_CHAT_MESSAGE (MEMORY_KEY, TURN_NO, MESSAGE_ORDER);
CREATE INDEX IDX_AI_CHAT_MESSAGE_MEMORY_TIME_AI_CHAT_MESSAGE ON AI_CHAT_MESSAGE (MEMORY_KEY, UPDATE_TIME);
CREATE INDEX IDX_AI_CHAT_MESSAGE_ENV_TIME_AI_CHAT_MESSAGE ON AI_CHAT_MESSAGE (ENV_CODE, CREATE_TIME);
CREATE INDEX IDX_AI_CHAT_MESSAGE_TRACE_AI_CHAT_MESSAGE ON AI_CHAT_MESSAGE (TRACE_ID);


-- ASTRO_AI.AI_CHAT_SESSION DEFINITION

CREATE TABLE IF NOT EXISTS AI_CHAT_SESSION
(
    ID
    BIGINT
    NOT
    NULL,
    MEMORY_KEY
    VARCHAR
(
    128
) NOT NULL,
    SESSION_TITLE VARCHAR
(
    255
) DEFAULT NULL,
    SESSION_STATUS VARCHAR
(
    32
) DEFAULT NULL,
    LAST_MESSAGE_PREVIEW TEXT,
    LAST_MESSAGE_AT BIGINT DEFAULT NULL,
    MESSAGE_COUNT INT DEFAULT '0',
    PROMPT_TOKENS INT DEFAULT '0',
    COMPLETION_TOKENS INT DEFAULT '0',
    TOTAL_TOKENS INT DEFAULT '0',
    AGENT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    INSTANCE_KEY VARCHAR
(
    128
) DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    128
) DEFAULT NULL,
    ACCOUNT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    PROMPT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    TRACE_ID VARCHAR
(
    128
) DEFAULT NULL,
    EXT_JSON TEXT,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT NOT NULL DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
),
    CONSTRAINT UK_AI_CHAT_SESSION_MEMORY_ENV UNIQUE
(
    MEMORY_KEY,
    ENV_CODE
)
    );
CREATE INDEX IDX_AI_CHAT_SESSION_ENV_STATUS_TIME_AI_CHAT_SESSION ON AI_CHAT_SESSION (ENV_CODE, SESSION_STATUS, UPDATE_TIME);
CREATE INDEX IDX_AI_CHAT_SESSION_MEMORY_AI_CHAT_SESSION ON AI_CHAT_SESSION (MEMORY_KEY);


-- ASTRO_AI.AI_CONVERSATION DEFINITION

CREATE TABLE IF NOT EXISTS AI_CONVERSATION
(
    ID
    BIGINT
    NOT
    NULL,
    MEMORY_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    ROLE VARCHAR
(
    50
) DEFAULT NULL,
    CONTENT TEXT,
    MESSAGE_ORDER INT DEFAULT NULL,
    CONSUME_TOKENS INT DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    100
) DEFAULT NULL,
    AGENT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    PROMPT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    INSTANCE_KEY VARCHAR
(
    100
) DEFAULT NULL,
    ACCOUNT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_CONV_AGENT_ID_AI_CONVERSATION ON AI_CONVERSATION (AGENT_KEY);
CREATE INDEX IDX_AI_CONV_MODEL_ID_AI_CONVERSATION ON AI_CONVERSATION (MODEL_KEY);
CREATE INDEX IDX_AI_CONV_DELETED_AI_CONVERSATION ON AI_CONVERSATION (DELETED);


-- ASTRO_AI.AI_INSTANCE DEFINITION

CREATE TABLE IF NOT EXISTS AI_INSTANCE
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    INSTANCE_KEY VARCHAR
(
    100
) DEFAULT NULL,
    BIZ_KEY VARCHAR
(
    128
) DEFAULT NULL,
    AGENT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    ROUTE_STRATEGY VARCHAR
(
    50
) DEFAULT NULL,
    ROUTE_WEIGHT INT DEFAULT NULL,
    RESILIENCE_ENABLED VARCHAR
(
    10
) DEFAULT 'false',
    RESILIENCE_INSTANCE_NAME VARCHAR
(
    200
) DEFAULT NULL,
    CIRCUIT_BREAKER_ENABLED VARCHAR
(
    10
) DEFAULT 'false',
    CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD INT DEFAULT NULL,
    CIRCUIT_BREAKER_WAIT_DURATION BIGINT DEFAULT NULL,
    RETRY_ENABLED VARCHAR
(
    10
) DEFAULT 'false',
    RETRY_MAX_ATTEMPTS INT DEFAULT NULL,
    RETRY_WAIT_DURATION BIGINT DEFAULT NULL,
    TIMEOUT_ENABLED VARCHAR
(
    10
) DEFAULT 'false',
    TIMEOUT_DURATION BIGINT DEFAULT NULL,
    FALLBACK_ENABLED VARCHAR
(
    10
) DEFAULT 'false',
    FALLBACK_INSTANCE_KEY VARCHAR
(
    100
) DEFAULT NULL,
    MAX_TOKENS BIGINT DEFAULT NULL,
    TEMPERATURE DOUBLE DEFAULT NULL,
    PRESENCE_PENALTY DOUBLE DEFAULT NULL,
    FREQUENCY_PENALTY DOUBLE DEFAULT NULL,
    STOP_SEQUENCES TEXT,
    SEED INT DEFAULT NULL,
    TOP_P DOUBLE DEFAULT NULL,
    TOP_K INT DEFAULT NULL,
    STYLE VARCHAR
(
    100
) DEFAULT NULL,
    SIZE VARCHAR
(
    100
) DEFAULT NULL,
    DIMENSIONS VARCHAR
(
    100
) DEFAULT NULL,
    STATUS VARCHAR
(
    100
) DEFAULT NULL,
    INSTANCE_NAME VARCHAR
(
    100
) DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    100
) DEFAULT NULL,
    IS_DEFAULT VARCHAR
(
    100
) DEFAULT NULL,
    ACCOUNT_KEY VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );


-- ASTRO_AI.AI_MCP DEFINITION

CREATE TABLE IF NOT EXISTS AI_MCP
(
    ID
    BIGINT
    NOT
    NULL,
    MCP_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    SERVER_NAME VARCHAR
(
    255
) DEFAULT NULL,
    DESCRIPTION TEXT,
    TYPE VARCHAR
(
    50
) DEFAULT NULL,
    SSE_ADDRESS VARCHAR
(
    500
) DEFAULT NULL,
    REQUEST_HEADER_CONFIG TEXT,
    ENABLED INT DEFAULT NULL,
    COMMAND VARCHAR
(
    500
) DEFAULT NULL,
    ARGS TEXT,
    ENV_VARS TEXT,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_MCP_MCP_KEY_AI_MCP ON AI_MCP (MCP_KEY);
CREATE INDEX IDX_AI_MCP_ENABLED_AI_MCP ON AI_MCP (ENABLED);
CREATE INDEX IDX_AI_MCP_DELETED_AI_MCP ON AI_MCP (DELETED);


-- ASTRO_AI.AI_MODEL DEFINITION

CREATE TABLE IF NOT EXISTS AI_MODEL
(
    ID
    BIGINT
    NOT
    NULL,
    MODEL_NAME
    VARCHAR
(
    255
) DEFAULT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    255
) DEFAULT NULL,
    MODEL_TYPE VARCHAR
(
    100
) DEFAULT NULL,
    EXTENSION_CODE VARCHAR
(
    100
) DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    RESPONSE_LIMIT INT DEFAULT NULL,
    IS_DEFAULT VARCHAR
(
    50
) DEFAULT NULL,
    CAPABILITIES TEXT,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    MAX_QUOTA_TOKENS BIGINT DEFAULT NULL,
    PARAMS TEXT,
    SOURCE_TYPE VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_MODEL_MODEL_KEY_AI_MODEL ON AI_MODEL (MODEL_KEY);
CREATE INDEX IDX_AI_MODEL_STATUS_AI_MODEL ON AI_MODEL (STATUS);
CREATE INDEX IDX_AI_MODEL_IS_DEFAULT_AI_MODEL ON AI_MODEL (IS_DEFAULT);
CREATE INDEX IDX_AI_MODEL_DELETED_AI_MODEL ON AI_MODEL (DELETED);


-- ASTRO_AI.AI_PROMPT DEFINITION

CREATE TABLE IF NOT EXISTS AI_PROMPT
(
    ID
    BIGINT
    NOT
    NULL,
    PROMPT_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    PROMPT_TITLE VARCHAR
(
    255
) DEFAULT NULL,
    PROMPT_CONTENT TEXT,
    SCENE VARCHAR
(
    100
) DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    VERSION INT DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_PROMPT_PROMPT_KEY_AI_PROMPT ON AI_PROMPT (PROMPT_KEY);
CREATE INDEX IDX_AI_PROMPT_SCENE_AI_PROMPT ON AI_PROMPT (SCENE);
CREATE INDEX IDX_AI_PROMPT_VERSION_AI_PROMPT ON AI_PROMPT (VERSION);
CREATE INDEX IDX_AI_PROMPT_DELETED_AI_PROMPT ON AI_PROMPT (DELETED);


-- ASTRO_AI.AI_SENSITIVE_WORD DEFINITION

CREATE TABLE IF NOT EXISTS AI_SENSITIVE_WORD
(
    ID
    BIGINT
    NOT
    NULL,
    WORD
    VARCHAR
(
    255
) NOT NULL,
    MATCH_TYPE VARCHAR
(
    20
) DEFAULT 'FUZZY',
    SCOPE_KEY VARCHAR
(
    50
) DEFAULT 'ALL',
    ACTION VARCHAR
(
    20
) DEFAULT 'BLOCK',
    REPLACEMENT VARCHAR
(
    255
) DEFAULT NULL,
    CATEGORY VARCHAR
(
    50
) DEFAULT NULL,
    STATUS VARCHAR
(
    20
) DEFAULT 'ENABLED',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    20
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_WORD_AI_SENSITIVE_WORD ON AI_SENSITIVE_WORD (WORD);
CREATE INDEX IDX_SCOPE_STATUS_AI_SENSITIVE_WORD ON AI_SENSITIVE_WORD (SCOPE_KEY, STATUS);


-- ASTRO_AI.AI_TEMPLATE DEFINITION

CREATE TABLE IF NOT EXISTS AI_TEMPLATE
(
    ID
    BIGINT
    NOT
    NULL,
    TEMPLATE_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    TEMPLATE_TITLE VARCHAR
(
    255
) DEFAULT NULL,
    CONTENT TEXT,
    CATEGORY VARCHAR
(
    100
) DEFAULT NULL,
    TEMPLATE_TYPE VARCHAR
(
    50
) DEFAULT NULL,
    VERSION INT DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_TEMPLATE_TEMPLATE_KEY_AI_TEMPLATE ON AI_TEMPLATE (TEMPLATE_KEY);
CREATE INDEX IDX_AI_TEMPLATE_CATEGORY_AI_TEMPLATE ON AI_TEMPLATE (CATEGORY);
CREATE INDEX IDX_AI_TEMPLATE_VERSION_AI_TEMPLATE ON AI_TEMPLATE (VERSION);
CREATE INDEX IDX_AI_TEMPLATE_DELETED_AI_TEMPLATE ON AI_TEMPLATE (DELETED);


-- ASTRO_AI.AI_TOOL DEFINITION

CREATE TABLE IF NOT EXISTS AI_TOOL
(
    ID
    BIGINT
    NOT
    NULL,
    TOOL_NAME
    VARCHAR
(
    255
) DEFAULT NULL,
    TOOL_KEY VARCHAR
(
    255
) DEFAULT NULL,
    DESCRIPTION TEXT,
    BEAN_NAME VARCHAR
(
    255
) DEFAULT NULL,
    METHOD_NAME VARCHAR
(
    255
) DEFAULT NULL,
    TYPE VARCHAR
(
    50
) DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    CLASS_NAME VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AI_TOOL_TOOL_KEY_AI_TOOL ON AI_TOOL (TOOL_KEY);
CREATE INDEX IDX_AI_TOOL_TYPE_AI_TOOL ON AI_TOOL (TYPE);
CREATE INDEX IDX_AI_TOOL_DELETED_AI_TOOL ON AI_TOOL (DELETED);


-- ASTRO_AI.AI_TRACE_LOG DEFINITION

CREATE TABLE IF NOT EXISTS AI_TRACE_LOG
(
    ID
    BIGINT
    NOT
    NULL,
    TRACE_ID
    VARCHAR
(
    64
) DEFAULT NULL,
    CONVERSATION_ID BIGINT DEFAULT NULL,
    AGENT_ID BIGINT DEFAULT NULL,
    INSTANCE_ID BIGINT DEFAULT NULL,
    PROMPT_ID BIGINT DEFAULT NULL,
    AGENT_KEY VARCHAR
(
    128
) DEFAULT NULL,
    BIZ_KEY VARCHAR
(
    128
) DEFAULT NULL,
    SNAPSHOT_CONTENT TEXT,
    NODE_TYPE VARCHAR
(
    32
) DEFAULT NULL,
    INPUT_DATA TEXT,
    OUTPUT_DATA TEXT,
    CONSUME_TOKENS INT DEFAULT NULL,
    DURATION BIGINT DEFAULT NULL,
    STATUS VARCHAR
(
    16
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_TRACE_ID_AI_TRACE_LOG ON AI_TRACE_LOG (TRACE_ID);
CREATE INDEX IDX_CONVERSATION_ID_AI_TRACE_LOG ON AI_TRACE_LOG (CONVERSATION_ID);
CREATE INDEX IDX_AGENT_ID_AI_TRACE_LOG ON AI_TRACE_LOG (AGENT_ID);
CREATE INDEX IDX_INSTANCE_ID_AI_TRACE_LOG ON AI_TRACE_LOG (INSTANCE_ID);
CREATE INDEX IDX_STATUS_AI_TRACE_LOG ON AI_TRACE_LOG (STATUS);
CREATE INDEX IDX_CREATE_TIME_AI_TRACE_LOG ON AI_TRACE_LOG (CREATE_TIME);
CREATE INDEX IDX_ENV_CODE_AI_TRACE_LOG ON AI_TRACE_LOG (ENV_CODE);


-- ASTRO_AI.AI_VEC_DOC DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_DOC
(
    ID
    BIGINT
    NOT
    NULL,
    COLLECTION_ID
    BIGINT
    DEFAULT
    NULL,
    DOC_ID_IN_STORE
    VARCHAR
(
    128
) DEFAULT NULL,
    CONTENT_SUMMARY VARCHAR
(
    512
) DEFAULT NULL,
    SYNC_STATUS VARCHAR
(
    32
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    FILE_PATH VARCHAR
(
    100
) DEFAULT NULL,
    FILE_RECORD_ID BIGINT DEFAULT NULL,
    ORIGINAL_FILE_NAME VARCHAR
(
    100
) DEFAULT NULL,
    VECTORIZE_PROGRESS INT DEFAULT NULL,
    VECTORIZE_MSG TEXT,
    VECTORIZE_TASK_ID VARCHAR
(
    128
) DEFAULT NULL,
    TOTAL_SEGMENTS INT DEFAULT NULL,
    DONE_SEGMENTS INT DEFAULT NULL,
    FOLDER_ID BIGINT DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_COLLECTION_ID_AI_VEC_DOC ON AI_VEC_DOC (COLLECTION_ID);
CREATE INDEX IDX_DOC_ID_IN_STORE_AI_VEC_DOC ON AI_VEC_DOC (DOC_ID_IN_STORE);
CREATE INDEX IDX_SYNC_STATUS_AI_VEC_DOC ON AI_VEC_DOC (SYNC_STATUS);
CREATE INDEX IDX_CREATE_TIME_AI_VEC_DOC ON AI_VEC_DOC (CREATE_TIME);
CREATE INDEX IDX_ENV_CODE_AI_VEC_DOC ON AI_VEC_DOC (ENV_CODE);


-- ASTRO_AI.AI_VEC_DRIVER DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_DRIVER
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    DRIVER_NAME VARCHAR
(
    100
) DEFAULT NULL,
    PROVIDER VARCHAR
(
    100
) DEFAULT NULL,
    PARAMS VARCHAR
(
    100
) DEFAULT NULL,
    STATUS VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );


-- ASTRO_AI.AI_VEC_SEGMENT DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_SEGMENT
(
    ID
    BIGINT
    NOT
    NULL,
    DOC_ID
    BIGINT
    DEFAULT
    NULL,
    COLLECTION_ID
    BIGINT
    DEFAULT
    NULL,
    VECTOR_ID
    VARCHAR
(
    128
) DEFAULT NULL,
    SEGMENT_CONTENT TEXT,
    WORD_COUNT BIGINT DEFAULT NULL,
    CHUNK_INDEX BIGINT DEFAULT NULL,
    METADATA_JSON TEXT,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_DOC_ID_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (DOC_ID);
CREATE INDEX IDX_COLLECTION_ID_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (COLLECTION_ID);
CREATE INDEX IDX_VECTOR_ID_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (VECTOR_ID);
CREATE INDEX IDX_CHUNK_INDEX_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (CHUNK_INDEX);
CREATE INDEX IDX_CREATE_TIME_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (CREATE_TIME);
CREATE INDEX IDX_ENV_CODE_AI_VEC_SEGMENT ON AI_VEC_SEGMENT (ENV_CODE);


-- ASTRO_AI.AI_VEC_SOURCE DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_SOURCE
(
    ID
    BIGINT
    NOT
    NULL,
    NAME
    VARCHAR
(
    128
) DEFAULT NULL,
    EXTENSION_CODE VARCHAR
(
    64
) DEFAULT NULL,
    HOST VARCHAR
(
    256
) DEFAULT NULL,
    PORT VARCHAR
(
    16
) DEFAULT NULL,
    USERNAME VARCHAR
(
    128
) DEFAULT NULL,
    PASSWORD VARCHAR
(
    256
) DEFAULT NULL,
    DATABASE_NAME VARCHAR
(
    128
) DEFAULT NULL,
    TOKEN VARCHAR
(
    512
) DEFAULT NULL,
    CONFIG_JSON TEXT,
    STATUS VARCHAR
(
    32
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_NAME_AI_VEC_SOURCE ON AI_VEC_SOURCE (NAME);
CREATE INDEX IDX_PROVIDER_AI_VEC_SOURCE ON AI_VEC_SOURCE (EXTENSION_CODE);
CREATE INDEX IDX_STATUS_AI_VEC_SOURCE ON AI_VEC_SOURCE (STATUS);
CREATE INDEX IDX_CREATE_TIME_AI_VEC_SOURCE ON AI_VEC_SOURCE (CREATE_TIME);
CREATE INDEX IDX_ENV_CODE_AI_VEC_SOURCE ON AI_VEC_SOURCE (ENV_CODE);


-- ASTRO_AI.AI_VEC_STORE DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_STORE
(
    ID
    BIGINT
    NOT
    NULL,
    SOURCE_ID
    BIGINT
    DEFAULT
    NULL,
    COLLECTION_NAME
    VARCHAR
(
    128
) DEFAULT NULL,
    DIMENSION BIGINT DEFAULT NULL,
    DISTANCE_METRIC VARCHAR
(
    32
) DEFAULT NULL,
    METADATA_SCHEMA TEXT,
    INSTANCE_KEY VARCHAR
(
    100
) DEFAULT NULL,
    MODEL_KEY VARCHAR
(
    128
) DEFAULT NULL,
    CHUNK_STRATEGY VARCHAR
(
    50
) DEFAULT NULL,
    CHUNK_SIZE INT DEFAULT NULL,
    CHUNK_OVERLAP INT DEFAULT NULL,
    DENSE_WEIGHT DECIMAL
(
    10,4
) DEFAULT NULL,
    INSTRUCTION_PREFIX TEXT,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_SOURCE_ID_AI_VEC_STORE ON AI_VEC_STORE (SOURCE_ID);
CREATE INDEX IDX_COLLECTION_NAME_AI_VEC_STORE ON AI_VEC_STORE (COLLECTION_NAME);
CREATE INDEX IDX_MODEL_KEY_AI_VEC_STORE ON AI_VEC_STORE (MODEL_KEY);
CREATE INDEX IDX_CREATE_TIME_AI_VEC_STORE ON AI_VEC_STORE (CREATE_TIME);
CREATE INDEX IDX_ENV_CODE_AI_VEC_STORE ON AI_VEC_STORE (ENV_CODE);


-- ASTRO_AI.AI_VEC_FOLDER DEFINITION

CREATE TABLE IF NOT EXISTS AI_VEC_FOLDER
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    COLLECTION_ID BIGINT DEFAULT NULL,
    FOLDER_NAME VARCHAR
(
    128
) DEFAULT NULL,
    PARENT_ID BIGINT DEFAULT NULL,
    SORT_ORDER INT DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_COLLECTION_ID_AI_VEC_FOLDER ON AI_VEC_FOLDER (COLLECTION_ID);
CREATE INDEX IDX_PARENT_ID_AI_VEC_FOLDER ON AI_VEC_FOLDER (PARENT_ID);


-- ASTRO_AI.AST_FLOW_BIZ_IDEMPOTENT DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_BIZ_IDEMPOTENT
(
    ID
    BIGINT
    NOT
    NULL,
    IDEMPOTENT_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    BIZ_TYPE VARCHAR
(
    100
) DEFAULT NULL,
    BIZ_ID VARCHAR
(
    255
) DEFAULT NULL,
    REQUEST_HASH VARCHAR
(
    255
) DEFAULT NULL,
    RESULT_REF VARCHAR
(
    255
) DEFAULT NULL,
    EXPIRE_AT_MS BIGINT DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
),
    CONSTRAINT UK_IDEMPOTENT_KEY UNIQUE
(
    IDEMPOTENT_KEY
)
    );
CREATE INDEX IDX_BIZ_ID_AST_FLOW_BIZ_IDEMPOTENT ON AST_FLOW_BIZ_IDEMPOTENT (BIZ_ID);
CREATE INDEX IDX_EXPIRE_AT_MS_AST_FLOW_BIZ_IDEMPOTENT ON AST_FLOW_BIZ_IDEMPOTENT (EXPIRE_AT_MS);
CREATE INDEX IDX_DELETED_AST_FLOW_BIZ_IDEMPOTENT ON AST_FLOW_BIZ_IDEMPOTENT (DELETED);


-- ASTRO_AI.AST_FLOW_DEFINITION DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_DEFINITION
(
    ID
    BIGINT
    NOT
    NULL,
    NAME
    VARCHAR
(
    255
) DEFAULT NULL,
    FLOW_KEY VARCHAR
(
    255
) DEFAULT NULL,
    CATEGORY VARCHAR
(
    100
) DEFAULT NULL,
    DRAFT_GRAPH_JSON LONGTEXT,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_FLOW_KEY_AST_FLOW_DEFINITION ON AST_FLOW_DEFINITION (FLOW_KEY);
CREATE INDEX IDX_DELETED_AST_FLOW_DEFINITION ON AST_FLOW_DEFINITION (DELETED);


-- ASTRO_AI.AST_FLOW_DEPLOYMENT DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_DEPLOYMENT
(
    ID
    BIGINT
    NOT
    NULL,
    FLOW_DEFINITION_ID
    BIGINT
    DEFAULT
    NULL,
    VERSION
    INT
    DEFAULT
    NULL,
    DEPLOYED_GRAPH_JSON
    LONGTEXT,
    IS_LATEST
    TINYINT
    DEFAULT
    NULL,
    CREATE_TIME
    DATETIME
    DEFAULT
    NULL,
    UPDATE_TIME
    DATETIME
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_FLOW_DEFINITION_ID_AST_FLOW_DEPLOYMENT ON AST_FLOW_DEPLOYMENT (FLOW_DEFINITION_ID);
CREATE INDEX IDX_VERSION_AST_FLOW_DEPLOYMENT ON AST_FLOW_DEPLOYMENT (VERSION);
CREATE INDEX IDX_IS_LATEST_AST_FLOW_DEPLOYMENT ON AST_FLOW_DEPLOYMENT (IS_LATEST);
CREATE INDEX IDX_DELETED_AST_FLOW_DEPLOYMENT ON AST_FLOW_DEPLOYMENT (DELETED);


-- ASTRO_AI.AST_FLOW_HUMAN_TASK DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_HUMAN_TASK
(
    ID
    BIGINT
    NOT
    NULL,
    INSTANCE_ID
    BIGINT
    DEFAULT
    NULL,
    NODE_ID
    VARCHAR
(
    255
) DEFAULT NULL,
    TASK_STATUS VARCHAR
(
    50
) DEFAULT NULL,
    PAYLOAD LONGTEXT,
    ACTION_DATA LONGTEXT,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_INSTANCE_ID_AST_FLOW_HUMAN_TASK ON AST_FLOW_HUMAN_TASK (INSTANCE_ID);
CREATE INDEX IDX_NODE_ID_AST_FLOW_HUMAN_TASK ON AST_FLOW_HUMAN_TASK (NODE_ID);
CREATE INDEX IDX_TASK_STATUS_AST_FLOW_HUMAN_TASK ON AST_FLOW_HUMAN_TASK (TASK_STATUS);
CREATE INDEX IDX_DELETED_AST_FLOW_HUMAN_TASK ON AST_FLOW_HUMAN_TASK (DELETED);


-- ASTRO_AI.AST_FLOW_INSTANCE DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_INSTANCE
(
    ID
    BIGINT
    NOT
    NULL,
    DEPLOYMENT_ID
    BIGINT
    DEFAULT
    NULL,
    BUSINESS_KEY
    VARCHAR
(
    255
) DEFAULT NULL,
    EXECUTION_STATUS VARCHAR
(
    50
) DEFAULT NULL,
    CURRENT_NODE_ID VARCHAR
(
    255
) DEFAULT NULL,
    STATE_JSON LONGTEXT,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_DEPLOYMENT_ID_AST_FLOW_INSTANCE ON AST_FLOW_INSTANCE (DEPLOYMENT_ID);
CREATE INDEX IDX_BUSINESS_KEY_AST_FLOW_INSTANCE ON AST_FLOW_INSTANCE (BUSINESS_KEY);
CREATE INDEX IDX_EXECUTION_STATUS_AST_FLOW_INSTANCE ON AST_FLOW_INSTANCE (EXECUTION_STATUS);
CREATE INDEX IDX_DELETED_AST_FLOW_INSTANCE ON AST_FLOW_INSTANCE (DELETED);


-- ASTRO_AI.AST_FLOW_INSTANCE_EVENT DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_INSTANCE_EVENT
(
    ID
    BIGINT
    NOT
    NULL,
    INSTANCE_ID
    BIGINT
    DEFAULT
    NULL,
    EVENT_TYPE
    VARCHAR
(
    100
) DEFAULT NULL,
    NODE_ID VARCHAR
(
    255
) DEFAULT NULL,
    EVENT_TIME_MS BIGINT DEFAULT NULL,
    EVENT_DATA_JSON LONGTEXT,
    TRACE_ID VARCHAR
(
    255
) DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_INSTANCE_ID_AST_FLOW_INSTANCE_EVENT ON AST_FLOW_INSTANCE_EVENT (INSTANCE_ID);
CREATE INDEX IDX_EVENT_TYPE_AST_FLOW_INSTANCE_EVENT ON AST_FLOW_INSTANCE_EVENT (EVENT_TYPE);
CREATE INDEX IDX_TRACE_ID_AST_FLOW_INSTANCE_EVENT ON AST_FLOW_INSTANCE_EVENT (TRACE_ID);
CREATE INDEX IDX_DELETED_AST_FLOW_INSTANCE_EVENT ON AST_FLOW_INSTANCE_EVENT (DELETED);


-- ASTRO_AI.AST_FLOW_MSG_OUTBOX DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_MSG_OUTBOX
(
    ID
    BIGINT
    NOT
    NULL,
    BIZ_TYPE
    VARCHAR
(
    100
) DEFAULT NULL,
    BIZ_ID VARCHAR
(
    255
) DEFAULT NULL,
    TOPIC_OR_ENDPOINT VARCHAR
(
    255
) DEFAULT NULL,
    PAYLOAD_JSON LONGTEXT,
    MSG_STATUS VARCHAR
(
    50
) DEFAULT NULL,
    RETRY_COUNT INT DEFAULT NULL,
    NEXT_RETRY_TIME_MS BIGINT DEFAULT NULL,
    LAST_ERROR LONGTEXT,
    IDEMPOTENT_KEY VARCHAR
(
    255
) DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_BIZ_ID_AST_FLOW_MSG_OUTBOX ON AST_FLOW_MSG_OUTBOX (BIZ_ID);
CREATE INDEX IDX_MSG_STATUS_AST_FLOW_MSG_OUTBOX ON AST_FLOW_MSG_OUTBOX (MSG_STATUS);
CREATE INDEX IDX_IDEMPOTENT_KEY_AST_FLOW_MSG_OUTBOX ON AST_FLOW_MSG_OUTBOX (IDEMPOTENT_KEY);
CREATE INDEX IDX_DELETED_AST_FLOW_MSG_OUTBOX ON AST_FLOW_MSG_OUTBOX (DELETED);


-- ASTRO_AI.AST_FLOW_NODE_CONFIG DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_NODE_CONFIG
(
    ID
    BIGINT
    NOT
    NULL,
    FLOW_DEFINITION_ID
    BIGINT
    DEFAULT
    NULL,
    NODE_ID
    VARCHAR
(
    255
) DEFAULT NULL,
    NODE_TYPE VARCHAR
(
    100
) DEFAULT NULL,
    CONFIG_JSON LONGTEXT,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_FLOW_DEFINITION_ID_AST_FLOW_NODE_CONFIG ON AST_FLOW_NODE_CONFIG (FLOW_DEFINITION_ID);
CREATE INDEX IDX_NODE_ID_AST_FLOW_NODE_CONFIG ON AST_FLOW_NODE_CONFIG (NODE_ID);
CREATE INDEX IDX_NODE_TYPE_AST_FLOW_NODE_CONFIG ON AST_FLOW_NODE_CONFIG (NODE_TYPE);
CREATE INDEX IDX_DELETED_AST_FLOW_NODE_CONFIG ON AST_FLOW_NODE_CONFIG (NODE_DELETED);


-- ASTRO_AI.AST_FLOW_NODE_HISTORY DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_NODE_HISTORY
(
    ID
    BIGINT
    NOT
    NULL,
    INSTANCE_ID
    BIGINT
    DEFAULT
    NULL,
    FLOW_DEFINITION_ID
    BIGINT
    DEFAULT
    NULL,
    VERSION
    INT
    DEFAULT
    NULL,
    HISTORY_TYPE
    VARCHAR
(
    50
) DEFAULT NULL,
    NODE_ID VARCHAR
(
    255
) DEFAULT NULL,
    NODE_NAME VARCHAR
(
    255
) DEFAULT NULL,
    INPUT_DATA LONGTEXT,
    OUTPUT_DATA LONGTEXT,
    SNAPSHOT_JSON LONGTEXT,
    EXECUTION_MS BIGINT DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_INSTANCE_ID_AST_FLOW_NODE_HISTORY ON AST_FLOW_NODE_HISTORY (INSTANCE_ID);
CREATE INDEX IDX_FLOW_DEFINITION_ID_AST_FLOW_NODE_HISTORY ON AST_FLOW_NODE_HISTORY (FLOW_DEFINITION_ID);
CREATE INDEX IDX_NODE_ID_AST_FLOW_NODE_HISTORY ON AST_FLOW_NODE_HISTORY (NODE_ID);
CREATE INDEX IDX_DELETED_AST_FLOW_NODE_HISTORY ON AST_FLOW_NODE_HISTORY (DELETED);


-- ASTRO_AI.AST_FLOW_TIMER_JOB DEFINITION

CREATE TABLE IF NOT EXISTS AST_FLOW_TIMER_JOB
(
    ID
    BIGINT
    NOT
    NULL,
    INSTANCE_ID
    BIGINT
    DEFAULT
    NULL,
    NODE_ID
    VARCHAR
(
    255
) DEFAULT NULL,
    JOB_TYPE VARCHAR
(
    100
) DEFAULT NULL,
    DUE_TIME_MS BIGINT DEFAULT NULL,
    JOB_STATUS VARCHAR
(
    50
) DEFAULT NULL,
    RETRY_COUNT INT DEFAULT NULL,
    MAX_RETRY INT DEFAULT NULL,
    LAST_ERROR LONGTEXT,
    PAYLOAD_JSON LONGTEXT,
    CREATE_TIME DATETIME DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_INSTANCE_ID_AST_FLOW_TIMER_JOB ON AST_FLOW_TIMER_JOB (INSTANCE_ID);
CREATE INDEX IDX_NODE_ID_AST_FLOW_TIMER_JOB ON AST_FLOW_TIMER_JOB (NODE_ID);
CREATE INDEX IDX_JOB_STATUS_AST_FLOW_TIMER_JOB ON AST_FLOW_TIMER_JOB (JOB_STATUS);
CREATE INDEX IDX_DUE_TIME_MS_AST_FLOW_TIMER_JOB ON AST_FLOW_TIMER_JOB (DUE_TIME_MS);
CREATE INDEX IDX_DELETED_AST_FLOW_TIMER_JOB ON AST_FLOW_TIMER_JOB (DELETED);


-- ASTRO_AI.AST_FILE_RECORD DEFINITION

CREATE TABLE IF NOT EXISTS AST_FILE_RECORD
(
    ID
    BIGINT
    NOT
    NULL,
    BIZ_TYPE
    VARCHAR
(
    64
) DEFAULT NULL,
    BIZ_ID VARCHAR
(
    128
) DEFAULT NULL,
    PLATFORM VARCHAR
(
    64
) DEFAULT NULL,
    BUCKET VARCHAR
(
    128
) DEFAULT NULL,
    OBJECT_KEY VARCHAR
(
    512
) DEFAULT NULL,
    ORIGIN_NAME VARCHAR
(
    255
) DEFAULT NULL,
    MIME_TYPE VARCHAR
(
    128
) DEFAULT NULL,
    FILE_SIZE BIGINT DEFAULT NULL,
    ETAG VARCHAR
(
    128
) DEFAULT NULL,
    STATUS VARCHAR
(
    32
) DEFAULT NULL,
    FILE_URL VARCHAR
(
    1024
) DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT NOT NULL DEFAULT '0',
    ENV_CODE VARCHAR
(
    32
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_AFR_BIZ_AST_FILE_RECORD ON AST_FILE_RECORD (BIZ_TYPE, BIZ_ID);
CREATE INDEX IDX_AFR_OBJECT_KEY_AST_FILE_RECORD ON AST_FILE_RECORD (OBJECT_KEY);
CREATE INDEX IDX_AFR_CREATE_TIME_AST_FILE_RECORD ON AST_FILE_RECORD (CREATE_TIME);


-- ASTRO_AI.SYS_CONFIG DEFINITION

CREATE TABLE IF NOT EXISTS SYS_CONFIG
(
    ID
    BIGINT
    NOT
    NULL,
    CONFIG_KEY
    VARCHAR
(
    100
) NOT NULL,
    CONFIG_VALUE TEXT,
    CONFIG_GROUP VARCHAR
(
    50
) NOT NULL,
    DESCRIPTION VARCHAR
(
    255
) DEFAULT NULL,
    IS_SYSTEM TINYINT DEFAULT '0',
    STATUS VARCHAR
(
    20
) DEFAULT 'ENABLED',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    20
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
),
    CONSTRAINT UK_CONFIG_ENV UNIQUE
(
    CONFIG_KEY,
    ENV_CODE
)
    );


-- ASTRO_AI.SYS_ENV DEFINITION

CREATE TABLE IF NOT EXISTS SYS_ENV
(
    ID
    BIGINT
    NOT
    NULL,
    ENV_NAME
    VARCHAR
(
    100
) DEFAULT NULL,
    DESCRIPTION TEXT,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    ENV_KEY VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_SYSTEM_ENV_ENV_CODE_SYS_ENV ON SYS_ENV (ENV_CODE);
CREATE INDEX IDX_SYSTEM_ENV_DELETED_SYS_ENV ON SYS_ENV (DELETED);


-- ASTRO_AI.SYS_EXTENSION DEFINITION

CREATE TABLE IF NOT EXISTS SYS_EXTENSION
(
    ID
    BIGINT
    NOT
    NULL,
    CREATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    UPDATE_TIME
    TIMESTAMP
    NULL
    DEFAULT
    NULL,
    CREATE_USER
    VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    STATUS VARCHAR
(
    50
) DEFAULT NULL,
    EXTENSION_KEY VARCHAR
(
    100
) DEFAULT NULL,
    EXTENSION_NAME VARCHAR
(
    100
) DEFAULT NULL,
    EXTENSION_CODE VARCHAR
(
    100
) DEFAULT NULL,
    TYPE VARCHAR
(
    100
) DEFAULT NULL,
    VERSION VARCHAR
(
    100
) DEFAULT NULL,
    AUTHOR VARCHAR
(
    100
) DEFAULT NULL,
    DESCRIPTION VARCHAR
(
    100
) DEFAULT NULL,
    JAR_NAME VARCHAR
(
    100
) DEFAULT NULL,
    APPLIED VARCHAR
(
    100
) DEFAULT NULL,
    AVATAR TEXT,
    DISCOVERY_MECHANISM VARCHAR
(
    100
) DEFAULT NULL,
    INSTALL_SOURCE VARCHAR
(
    100
) DEFAULT NULL,
    CHANGELOG VARCHAR
(
    100
) DEFAULT NULL,
    MIN_SERVER_VERSION VARCHAR
(
    100
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );


-- ASTRO_AI.SYS_MESSAGE DEFINITION

CREATE TABLE IF NOT EXISTS SYS_MESSAGE
(
    ID
    BIGINT
    NOT
    NULL,
    MESSAGE_TYPE
    VARCHAR
(
    64
) NOT NULL,
    MESSAGE_LEVEL VARCHAR
(
    32
) NOT NULL,
    READ_STATUS VARCHAR
(
    32
) NOT NULL DEFAULT 'UNREAD',
    TITLE VARCHAR
(
    255
) NOT NULL,
    CONTENT LONGTEXT,
    REF_TYPE VARCHAR
(
    64
) DEFAULT NULL,
    REF_ID BIGINT DEFAULT NULL,
    REF_KEY VARCHAR
(
    255
) DEFAULT NULL,
    SOURCE VARCHAR
(
    128
) DEFAULT NULL,
    ERROR_CODE VARCHAR
(
    128
) DEFAULT NULL,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    64
) DEFAULT NULL,
    DELETED TINYINT NOT NULL DEFAULT '0',
    ENV_CODE VARCHAR
(
    64
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_SYS_MSG_ENV_TIME_SYS_MESSAGE ON SYS_MESSAGE (ENV_CODE, CREATE_TIME);
CREATE INDEX IDX_SYS_MSG_TYPE_LEVEL_SYS_MESSAGE ON SYS_MESSAGE (MESSAGE_TYPE, MESSAGE_LEVEL);
CREATE INDEX IDX_SYS_MSG_READ_STATUS_SYS_MESSAGE ON SYS_MESSAGE (READ_STATUS);
CREATE INDEX IDX_SYS_MSG_REF_SYS_MESSAGE ON SYS_MESSAGE (REF_TYPE, REF_ID);
CREATE INDEX IDX_SYS_MSG_REF_KEY_SYS_MESSAGE ON SYS_MESSAGE (REF_KEY);
CREATE INDEX IDX_SYS_MSG_SOURCE_SYS_MESSAGE ON SYS_MESSAGE (SOURCE);
CREATE INDEX IDX_SYS_MSG_DELETED_SYS_MESSAGE ON SYS_MESSAGE (DELETED);


-- ASTRO_AI.SYS_USER DEFINITION

CREATE TABLE IF NOT EXISTS SYS_USER
(
    ID
    BIGINT
    NOT
    NULL,
    USERNAME
    VARCHAR
(
    100
) DEFAULT NULL,
    PASSWORD VARCHAR
(
    255
) DEFAULT NULL,
    ADMIN_FLAG VARCHAR
(
    50
) DEFAULT NULL,
    USER_ROLE VARCHAR
(
    32
) DEFAULT NULL,
    EMAIL VARCHAR
(
    255
) DEFAULT NULL,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    UPDATE_USER VARCHAR
(
    100
) DEFAULT NULL,
    DELETED TINYINT DEFAULT '0',
    ENV_CODE VARCHAR
(
    50
) DEFAULT NULL,
    PRIMARY KEY
(
    ID
)
    );
CREATE INDEX IDX_SYSTEM_USER_USERNAME_SYS_USER ON SYS_USER (USERNAME);
CREATE INDEX IDX_SYSTEM_USER_EMAIL_SYS_USER ON SYS_USER (EMAIL);
CREATE INDEX IDX_SYSTEM_USER_DELETED_SYS_USER ON SYS_USER (DELETED);