astrsomn:
  data-base:
    database-type: oracle
    host: 127.0.0.1
    port: 1521
    database-name: ORCL
    username: astro_ai
    password: astro_ai
    driver: oracle.jdbc.OracleDriver
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 5
