<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.astrsomn</groupId>
        <artifactId>astrsomn-plugins</artifactId>
        <version>0.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>astrsomn-providers</artifactId>
    <packaging>pom</packaging>
    <name>astrsomn-providers</name>
    <description>Astrsomn providers aggregate module</description>

    <properties>
        <langchain4j.version>1.11.0</langchain4j.version>
    </properties>

    <modules>
        <module>astrsomn-provider-deepseek</module>
        <module>astrsomn-provider-qwen</module>
        <module>astrsomn-provider-openai</module>
        <module>astrsomn-provider-qianfan</module>
        <module>astrsomn-provider-zhipu</module>
    </modules>


    <dependencies>
        <dependency>
            <groupId>com.astrsomn</groupId>
            <artifactId>astrsomn-api-runtime</artifactId>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-zhipu-ai</artifactId>
            <version>1.11.0-beta19</version>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-qianfan</artifactId>
            <version>1.11.0-beta19</version>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-google-ai-gemini</artifactId>
            <version>${langchain4j.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-jina</artifactId>
            <version>1.11.0-beta19</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>extension.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>extension.properties</exclude>
                </excludes>
            </resource>
        </resources>
    </build>

</project>

