<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.astrsomn</groupId>
        <artifactId>astrsomn-providers</artifactId>
        <version>0.1.0-alpha.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>astrsomn-provider-qwen</artifactId>
    <name>astrsomn-provider-qwen</name>
    <description>astrsomn-provider-qwen</description>

    <dependencies>
        <dependency>
            <groupId>org.astrsomn</groupId>
            <artifactId>astrsomn-core</artifactId>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-dashscope</artifactId>
            <version>1.11.0-beta19</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
